### ISSUE TITLE
Hi, Excellent Idea - Is it Working?

### ISSUE THREAD

**Issue by shaneholloman** [tehrobber/civitai-one-click-dl#1]
Currently logged in to Civitiai and have this enabled in tampermonkey on chrome
The Image downlad button is eluding me
Very exciting : )

**Comment by tehrobber** [comment]
There's a bug because CivitAI is a SPA. If you refresh the page the button shows up, it doesn't work if you navigate to a model from another page.

I'm working on it.

**Comment by tehrobber** [comment]
![image](https://user-images.githubusercontent.com/83055339/218333265-1b5f6d85-fed2-41ba-87ca-c77b6089f1fc.png)

**Comment by tehrobber** [comment]
Version 1.1 includes fixes for the SPA routing issues. Try updating, and if it's still happening reopen this issue.
